plugins: # List of plugins of use on application
    - serverless-offline # Get your serverless configuration and run the server local
    - serverless-plugin-typescript-express

# Project name on the infrastructure created
service: xend-git-exam

provider:
  name: aws
  runtime: nodejs8.10 
  stage: dev 
  region: us-east-1 
  deploymentBucket: yourdeploymentbucket

custom:
  serverless-offline:
    port: 3000
  domains:
    live: live.domain
    release: release.domain
    development: dev.domain

functions:  
  # User 
  getUsers: 
    handler: src/server.handler 
    events: 
      - http: 
          path: users
          method: get

  createUser:
    handler: src/server.handler
    events:
      - http:
          path: users
          method: post
  #Organization
  joinOrganizationById:
    handler: src/server.handler
    events:
      - http:
          path: organization/join/{id}
          method: post

  getOrganizations: 
    handler: src/server.handler 
    events: 
      - http: 
          path: organizations
          method: get
  getOrganizationById:
    handler: src/server.handler
    events:
      - http:
          path: organization/{id}
          method: get
  createOrganization:
    handler: src/server.handler
    events:
      - http:
          path: organizations
          method: post

  getCommentsByOrganizationId: 
    handler: src/server.handler 
    events: 
      - http: 
          path: organization/{id}/comments
          method: get

  getUsersByOrganizationId: 
    handler: src/server.handler 
    events: 
      - http: 
          path: organization/{id}/users
          method: get
  #Comments

  deleteCommentsByOrganizationId: 
    handler: src/server.handler 
    events: 
      - http: 
          path: comments/organization/{id}
          method: delete
  getComments: 
    handler: src/server.handler 
    events: 
      - http: 
          path: comments
          method: get
  createComment:
    handler: src/server.handler
    events:
      - http:
          path: comments
          method: post