plugins: # List of plugins of use on application
    - serverless-offline # Get your serverless configuration and run the server local
    - serverless-plugin-typescript-express

# Project name on the infrastructure created
service: node-typescript-serverless

provider:
  name: aws
  runtime: nodejs8.10 
  stage: dev 
  region: us-east-1 

custom:
  serverless-offline:
    port: 3005

functions:  
  # User 
  getUsers: 
    handler: src/server.handler 
    events: 
      - http: 
          path: users
          method: get
  getUserById:
    handler: src/server.handler
    events:
      - http:
          path: users/{id}
          method: get
  createUser:
    handler: src/server.handler
    events:
      - http:
          path: users
          method: post
  #Organization
  getOrganizations: 
    handler: src/server.handler 
    events: 
      - http: 
          path: organizations
          method: get
  getOrganizationById:
    handler: src/server.handler
    events:
      - http:
          path: organization/{id}
          method: get
  createOrganization:
    handler: src/server.handler
    events:
      - http:
          path: organizations
          method: post
  #Comments
  getComments: 
    handler: src/server.handler 
    events: 
      - http: 
          path: comments
          method: get
  getCommentId:
    handler: src/server.handler
    events:
      - http:
          path: comment/{id}
          method: get
  createComment:
    handler: src/server.handler
    events:
      - http:
          path: comments
          method: post